import type { Category, Product, Testimonial } from './types';

export const CATEGORIES: Category[] = [
    {
        id: 'cat-audio',
        name: 'Acoustics & Audio',
        description: 'Immersive soundscapes & noise cancellation engineered for purists.',
        slug: 'audio-tech',
        itemCount: 16,
        image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80',
    },
    {
        id: 'cat-workspace',
        name: 'Ergonomic Workspace',
        description: 'Architectural desk lamps, mechanical keyboards, and precision tools.',
        slug: 'workspace',
        itemCount: 24,
        image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=800&q=80',
    },
    {
        id: 'cat-apparel',
        name: 'Minimalist Apparel',
        description: 'Ultra-heavyweight French terry cotton & sustainably sourced weaves.',
        slug: 'apparel',
        itemCount: 32,
        image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
    },
    {
        id: 'cat-accessories',
        name: 'Craft Accessories',
        description: 'Titanium timepieces, full-grain leather goods, and RFID wallets.',
        slug: 'accessories',
        itemCount: 18,
        image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
    },
    {
        id: 'cat-home',
        name: 'Modern Living',
        description: 'Stoneware ceramics, ambient lighting, and artisanal soy candles.',
        slug: 'home-living',
        itemCount: 20,
        image: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80',
    },
];

export const PRODUCTS: Product[] = [
    {
        id: 'prod-1',
        name: 'Aura Horizon ANC Headphones',
        subtitle: 'Bespoke 40mm Beryllium Drivers',
        description:
            'Engineered with hybrid active noise cancellation, lossless Bluetooth 5.3, memory foam lambskin pads, and an exceptional 38-hour battery reserve.',
        price: 299,
        originalPrice: 350,
        rating: 4.9,
        reviewsCount: 248,
        category: 'audio-tech',
        image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80',
        gallery: [
            'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80',
            'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=900&q=80',
            'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=900&q=80',
        ],
        tag: 'Bestseller',
        badgeVariant: 'default',
        colors: [
            { name: 'Matte Obsidian', hex: '#1C1917' },
            { name: 'Lunar Silver', hex: '#D6D3D1' },
            { name: 'Champagne Sand', hex: '#E7E5E4' },
        ],
        features: [
            'Hybrid Active Noise Cancellation (up to -42dB)',
            'Ultra-low latency wireless + lossless USB-C audio',
            '38-Hour Battery with Fast Charge (10 min = 5 hours)',
            'Customizable EQ profiles via companion mobile app',
        ],
        inStock: true,
        isFeatured: true,
        isSale: true,
    },
    {
        id: 'prod-2',
        name: 'Titanium Chrono Timepiece',
        subtitle: 'Swiss Movement & Sapphire Glass',
        description:
            'A minimalist automatic chronograph sculpted from aerospace-grade Grade 5 titanium, complemented by scratch-proof sapphire crystal and interchangeable straps.',
        price: 219,
        originalPrice: 280,
        rating: 4.8,
        reviewsCount: 134,
        category: 'accessories',
        image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80',
        gallery: [
            'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80',
            'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=900&q=80',
        ],
        tag: 'New Season',
        badgeVariant: 'secondary',
        colors: [
            { name: 'Brushed Titanium', hex: '#78716C' },
            { name: 'Stealth Black', hex: '#09090B' },
            { name: 'Olive Green', hex: '#3F4F38' },
        ],
        features: [
            'Grade 5 Aerospace Titanium case (40mm)',
            'Swiss Sellita automatic movement',
            'Double-domed anti-reflective sapphire crystal',
            'Water resistant to 10 ATM (100 meters)',
        ],
        inStock: true,
        isFeatured: true,
        isSale: true,
    },
    {
        id: 'prod-3',
        name: 'Sculpt Architectural Desk Lamp',
        subtitle: 'Touch Dimming & Qi Wireless Pad',
        description:
            'Precision-machined aircraft aluminum with balanced counterweights. Seamless capacitive touch slider with circadian rhythm warm-to-cool tuning.',
        price: 145,
        rating: 4.9,
        reviewsCount: 89,
        category: 'workspace',
        image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=80',
        gallery: [
            'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=80',
            'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=900&q=80',
        ],
        tag: 'Editor Choice',
        badgeVariant: 'outline',
        colors: [
            { name: 'Carbon Black', hex: '#18181B' },
            { name: 'Warm White', hex: '#F4F4F5' },
        ],
        features: [
            'High CRI >98 natural light spectrum',
            'Built-in 15W Qi fast wireless charging base',
            '360° frictionless fluid ball-joint movement',
            'Auto-dimming ambient light sensor',
        ],
        inStock: true,
        isFeatured: true,
    },
    {
        id: 'prod-4',
        name: 'Kevlar Pro Mechanical Keyboard',
        subtitle: 'Hot-Swap & Gasket Mount System',
        description:
            'A 75% compact mechanical masterpiece featuring lubed tactile switches, sound-absorbing Poron gaskets, and CNC anodized aluminum chassis.',
        price: 165,
        originalPrice: 195,
        rating: 4.9,
        reviewsCount: 312,
        category: 'workspace',
        image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80',
        gallery: [
            'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80',
            'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=900&q=80',
        ],
        tag: 'Popular',
        badgeVariant: 'secondary',
        colors: [
            { name: 'Slate Gray', hex: '#475569' },
            { name: 'Nordic White', hex: '#E2E8F0' },
            { name: 'Cyberpunk Violet', hex: '#4C1D95' },
        ],
        features: [
            'Factory-lubed Gateron Oil King linear switches',
            'Tri-mode: Bluetooth 5.2, 2.4GHz low-lag, USB-C',
            '4000mAh battery for up to 200 hours of typing',
            'Mac & Windows dual layout switchable',
        ],
        inStock: true,
        isFeatured: true,
        isSale: true,
    },
    {
        id: 'prod-5',
        name: 'Heavyweight Loopback Hoodie',
        subtitle: '480 GSM French Terry Cotton',
        description:
            'Custom knitted heavyweight organic cotton with a tailored oversized drape, double-layered hood without drawstrings, and rib-knit cuffs.',
        price: 98,
        originalPrice: 125,
        rating: 4.8,
        reviewsCount: 176,
        category: 'apparel',
        image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=900&q=80',
        gallery: [
            'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=900&q=80',
            'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&w=900&q=80',
        ],
        tag: '22% OFF',
        badgeVariant: 'destructive',
        colors: [
            { name: 'Oatmeal Heather', hex: '#E6E4DE' },
            { name: 'Washed Charcoal', hex: '#333333' },
            { name: 'Sage Leaf', hex: '#7D8C7C' },
        ],
        features: [
            '100% GOTS certified organic Aegean cotton',
            'Pre-shrunk vintage enzyme wash',
            'Clean blind stitching & reinforced seams',
            'Sustainably dyed with zero toxic chemicals',
        ],
        inStock: true,
        isFeatured: false,
        isSale: true,
    },
    {
        id: 'prod-6',
        name: 'Full-Grain Commuter Backpack',
        subtitle: 'Tuscan Leather & 16" Laptop Pocket',
        description:
            'Handmade vegetable-tanned leather bag built to endure decades of city travel. Features water-resistant canvas lining and discreet passport pocket.',
        price: 245,
        originalPrice: 290,
        rating: 4.9,
        reviewsCount: 94,
        category: 'accessories',
        image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80',
        gallery: [
            'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80',
            'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=900&q=80',
        ],
        tag: 'Bestseller',
        badgeVariant: 'default',
        colors: [
            { name: 'Cognac Saddle', hex: '#8B4513' },
            { name: 'Matte Onyx', hex: '#1C1917' },
        ],
        features: [
            'Full-grain Tuscan vegetable-tanned leather',
            'Padded sleeve fits up to 16" MacBook Pro',
            'Weatherproof YKK Excella zippers',
            'Ergonomic breathable back panel padding',
        ],
        inStock: true,
        isFeatured: true,
        isSale: true,
    },
    {
        id: 'prod-7',
        name: 'Ceramic Stoneware Pourer & Cup Set',
        subtitle: 'Hand-Thrown Speckled Glaze',
        description:
            'Artisanal coffee and tea serving kit crafted in small batches by master potters. Raw unglazed terracotta base meets velvety matte white top.',
        price: 64,
        rating: 4.7,
        reviewsCount: 62,
        category: 'home-living',
        image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=900&q=80',
        gallery: [
            'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=900&q=80',
        ],
        tag: 'Handmade',
        badgeVariant: 'outline',
        colors: [
            { name: 'Raw Sand', hex: '#D7C4B7' },
            { name: 'Basalt Charcoal', hex: '#374151' },
        ],
        features: [
            'High-fire durable stoneware ceramic',
            'Dishwasher and microwave safe',
            'Ergonomic heat-dissipating spout design',
            'Includes matching 320ml barista cup',
        ],
        inStock: true,
        isFeatured: false,
    },
    {
        id: 'prod-8',
        name: 'Aura Studio Pebble 360 Speaker',
        subtitle: '360° Omnidirectional Acoustic Sound',
        description:
            'A compact acoustic sphere with tactile milled-aluminum rotary volume ring, IP67 dust/waterproof rating, and multi-room stereo pairing.',
        price: 139,
        originalPrice: 169,
        rating: 4.9,
        reviewsCount: 182,
        category: 'audio-tech',
        image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=900&q=80',
        gallery: [
            'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=900&q=80',
            'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=900&q=80',
        ],
        tag: 'Trending',
        badgeVariant: 'secondary',
        colors: [
            { name: 'Forest Moss', hex: '#2D372E' },
            { name: 'Sandstone Grey', hex: '#CBD5E1' },
            { name: 'Terracotta Coral', hex: '#B45309' },
        ],
        features: [
            'Custom 45mm neodymium driver + passive sub',
            'TrueWireless stereo pairing with 2nd unit',
            '22-Hour non-stop battery life',
            'Integrated lanyard ring for portability',
        ],
        inStock: true,
        isFeatured: true,
        isSale: true,
    },
    {
        id: 'prod-9',
        name: 'Hinoki & Smoked Wood Soy Candle',
        subtitle: '100% Botanical Wax & Wood Wick',
        description:
            'Poured into mouth-blown amber glass with an aromatic profile of Japanese cedar, charred birch, and crisp citrus bergamot. Burns clean for 65 hours.',
        price: 38,
        rating: 4.9,
        reviewsCount: 115,
        category: 'home-living',
        image: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=900&q=80',
        tag: 'Clean Fragrance',
        badgeVariant: 'outline',
        colors: [
            { name: 'Amber Glow', hex: '#B45309' },
            { name: 'Frosted Smoke', hex: '#4B5563' },
        ],
        features: [
            'Non-toxic pure renewable soy wax',
            'FSC-certified crackling wooden wick',
            'Phthalate-free essential oil extracts',
            'Hand-poured in reusable glassware',
        ],
        inStock: true,
        isFeatured: false,
    },
    {
        id: 'prod-10',
        name: 'Everyday Relaxed Chino Trousers',
        subtitle: 'High-Density Mercerized Twill',
        description:
            'Tailored with a subtle taper, hidden elasticated comfort waistband, and deep slant pockets for effortless transitions between work and weekend.',
        price: 110,
        rating: 4.8,
        reviewsCount: 88,
        category: 'apparel',
        image: 'https://images.unsplash.com/photo-1479064555552-3ef4979f8908?auto=format&fit=crop&w=900&q=80',
        tag: 'New',
        badgeVariant: 'secondary',
        colors: [
            { name: 'Desert Khaki', hex: '#C2B280' },
            { name: 'Ink Navy', hex: '#1E293B' },
            { name: 'Olive Drab', hex: '#3B4D3C' },
        ],
        features: [
            '98% Organic Cotton, 2% Elastane for stretch',
            'Corozo nut buttons & reinforced bar-tacks',
            'Wrinkle-resistant fabric finish',
            'Designed for everyday durability',
        ],
        inStock: true,
        isFeatured: false,
    },
    {
        id: 'prod-11',
        name: 'MagCharge Dual Wireless Stand',
        subtitle: 'CNC Aluminum & Magnetic Alignment',
        description:
            'Elevate your nightstand or desk. Fast-charges iPhone and AirPods simultaneously with weighted silicone grip footing so it stays put.',
        price: 89,
        originalPrice: 115,
        rating: 4.8,
        reviewsCount: 142,
        category: 'workspace',
        image: 'https://images.unsplash.com/photo-1622445262464-84b14e0745b1?auto=format&fit=crop&w=900&q=80',
        tag: '23% OFF',
        badgeVariant: 'destructive',
        colors: [
            { name: 'Space Grey', hex: '#374151' },
            { name: 'Silver Matte', hex: '#E5E7EB' },
        ],
        features: [
            '15W Qi2 certified magnetic fast charging',
            'Dual device simultaneous output',
            'Weighted anti-slip base with cable routing',
            'LED indicator with auto-sleep sensor',
        ],
        inStock: true,
        isFeatured: false,
        isSale: true,
    },
    {
        id: 'prod-12',
        name: 'Slim MagSafe Bifold Wallet',
        subtitle: 'RFID Protection & Tuscan Leather',
        description:
            'Holds up to 8 cards and folded cash in an ultra-compact silhouette. Features quick thumb-swipe slot and internal RFID blocking foil.',
        price: 58,
        originalPrice: 75,
        rating: 4.9,
        reviewsCount: 203,
        category: 'accessories',
        image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=900&q=80',
        tag: 'Essential',
        badgeVariant: 'default',
        colors: [
            { name: 'Caramel Tan', hex: '#A16207' },
            { name: 'Midnight Blue', hex: '#1E3A8A' },
            { name: 'Obsidian Black', hex: '#0F172A' },
        ],
        features: [
            'Integrated high-strength MagSafe magnets',
            'Holds 8 cards + 6 folded bills',
            'Military-grade RFID radiation shield',
            'Guaranteed patina with age',
        ],
        inStock: true,
        isFeatured: false,
        isSale: true,
    },
];

export const TESTIMONIALS: Testimonial[] = [
    {
        id: 'test-1',
        author: 'Elena Rostova',
        role: 'Senior Product Designer at Framer',
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
        rating: 5,
        content:
            'The Aura Horizon headphones replaced both my Sony XM5s and my AirPods Max. The materials feel like a piece of bespoke architecture, and the soundstage is sublime.',
        productName: 'Aura Horizon ANC Headphones',
        verified: true,
    },
    {
        id: 'test-2',
        author: 'Marcus Vance',
        role: 'Architect & Creative Director',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
        rating: 5,
        content:
            'Rarely do you find an e-commerce brand where every single product matches the photos down to the micrometer. The Titanium Chronograph feels like a $1,000 Swiss piece.',
        productName: 'Titanium Chrono Timepiece',
        verified: true,
    },
    {
        id: 'test-3',
        author: 'Sophia Chen',
        role: 'Tech Lead & Remote Founder',
        avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80',
        rating: 5,
        content:
            'The Sculpt desk lamp transformed my workspace completely. Natural warm light that keeps my eyes refreshed during 10-hour coding sprints. Fast delivery too!',
        productName: 'Sculpt Architectural Desk Lamp',
        verified: true,
    },
];

export const BRAND_VALUES = [
    {
        title: 'Global Express Delivery',
        description: 'Complimentary expedited shipping on every order over $75.',
        icon: 'Truck',
    },
    {
        title: '30-Day Risk-Free Trial',
        description: 'Try in your space. Free doorstep returns and full refunds, no friction.',
        icon: 'RotateCcw',
    },
    {
        title: '2-Year Craftsmanship Guarantee',
        description: 'Built to endure. Comprehensive warranty against any hardware defect.',
        icon: 'ShieldCheck',
    },
    {
        title: 'Carbon Neutral by Design',
        description: '100% biodegradable packaging and carbon-offset freight transit.',
        icon: 'Leaf',
    },
];
